### ISSUE TITLE
Change URL Encoding

### ISSUE THREAD

**Issue by techeverri** [samsel/easy-url-params#2]
My example URL have `%2B` instead of `+` (plus sign). After **Process URL** event every `%2B` is replaced by `+` (plus sign)

e.g. Original URL `https://www.example.com/home?param=value%2Bwith%2Bplus` after **Process URL** and then **Reload Edited URL** this is the outcome `https://www.example.com/home?param=value+with+plus`

**Comment by samsel** [comment]
@techeverri can you please post the URL that you are trying to use?

**Comment by techeverri** [comment]
@samsel issue updated!

**Comment by samsel** [comment]
@techeverri I think that is the right behavior? what is your expectation?

**Comment by techeverri** [comment]
Ok
